### ISSUE TITLE
Incompatible with Silex ^1.3

### ISSUE THREAD

**Issue by tsantos84** [dflydev/dflydev-doctrine-orm-service-provider#69]
Have you plan to support Silex 1.3?

**Comment by dominikzogg** [comment]
@tsantos84 do you use the v1?

**Comment by tsantos84** [comment]
Hi @dominikzogg. I've just tried with v1 and installed properly. 

The last version of Silex should be supported by dflydev-doctrine-orm-service, shouldn't?

**Comment by dominikzogg** [comment]
@tsantos84 the newest version is for silex 2.0 / pimple 3.0

**Comment by tsantos84** [comment]
I'm bit confused. The last version of dflydev-doctrine-orm-service-provider is not stable yet? Doing composer require silex/silex brings to me the version 1.3 and not 2.0.

**Comment by dominikzogg** [comment]
2.0 is stable (which is latest version), its build for pimple 3.0 (which is also stable since long time) only silex 2.0 is not stable atm.

**Comment by tsantos84** [comment]
Hum...in this case I should use the version v1, right?

**Comment by dominikzogg** [comment]
yes

**Comment by tsantos84** [comment]
Ok @dominikzogg. Thanks by your support.

**Comment by dominikzogg** [comment]
@tsantos84 your welcome
