### ISSUE TITLE
Register doctrine behavior

### ISSUE THREAD

**Issue by PetarFedorovsky** [dflydev/dflydev-doctrine-orm-service-provider#80]
Hi, 
Could someone explain how to add  Sluggable, Translatable, Timestampable, Loggable, Tree and Sortable behaviors in Silex?

I'm trying to achieve:
https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/translatable.md#translation-entity

to have "page" table for non translatable part, and page_translations for translatable parts of a table.

Any help would be appreciated.

**Comment by ntelfer** [comment]
I found this Stackoverflow article helpful for this:
https://stackoverflow.com/questions/10676242/using-doctrine2-sluggable-extension-with-silex

**Comment by PetarFedorovsky** [comment]
> 
> 
> I found this Stackoverflow article helpful for this:
> https://stackoverflow.com/questions/10676242/using-doctrine2-sluggable-extension-with-silex

Tnx, but Silex is dead. Symfony 4 is basically what i was trying to achieve using silex.
